name: generate
on: 
  - workflow_dispatch
jobs:
    On_Linux:
        runs-on: ubuntu-latest
        steps:
          - name: Hello World
            uses: docker run hello-world
    On_Windows:
        runs-on: ubuntu-latest
        steps:
          - name: Hello World
            uses: docker run hello-world