name: Matrix Configuration

on: [push,workflow_dispatch]

jobs:
    On_Linux:
        runs-on: ubuntu-latest
        steps:
          - name: Echo Docker Details
            run: docker info

          - name: Hello World
            run: docker run hello-world
    On_Windows:
        runs-on: windows-latest
        steps:
          - name: Docker Details
            run: docker info 
          - name: Hello World
            run: docker run hello-world