name: Matrix Configuration

on:
  push:
  workflow_dispatch:

jobs:
    linux:
        runs-on: ubuntu-latest
        steps:
          - name: Echo Docker Details
            run: docker info

          - name: Hello World
            run: docker run hello-world
    windows:
        runs-on: windows-latest
        steps:
          - name: Docker Details
            run: docker info 
          - name: Hello World
            run: docker run hello-world