name: Matrix Configuration

on:
  push:
  workflow_dispatch:

jobs:
    deploy:
        strategy:
            matrix: 
                os: [ubuntu-latest,ubuntu-20.04,windows-lates]
                image: [hello-world,alpin]
        runs-on: ${{ matrix.os }}
        steps:
          - name: Echo Docker Details
            run: docker info
          - name: Hello World
            run: docker run ${{ matrix.image }}