name: Generate ASCII Using Multiple Jobs
on:
    workflow_dispatch:
env: 
    FILE-NAME: dragon-text-file
jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:

          - name: Install Cosway CLI
            run: sudo apt-get install cowsay -y 
        
          - name: Execute Cosway CMD
            run: cowsay -f dragon "RUN i am dragon" > dragon.txt

          - name: Upload Dragon text file
            uses: actions/upload-artifact@v4
            with:
                name: ${{ env.FILE-NAME }}
                path: dragon.txt
    test_job:
        runs-on: ubuntu-latest
        needs: build_job
        steps:
          - name: Get Dragon file
            uses: actions/download-artifact@v4
            with:
                name: ${{ env.FILE-NAME }}
          - name: Check if file exists
            run:  grep -i "dragon" dragon.txt

    deploy_job:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'
        needs: [test_job]
        concurrency:
            group: production-deployment
            cancel-in-progress: true
        steps:
         - name: Get Dragon file
           uses: actions/download-artifact@v4
           with:
                name: ${{ env.FILE-NAME }}
         - name: Read the file
           run:  cat dragon.txt
         - name: Deploy
           run: echo "Deploying"

    testing_var_sec:
        runs-on: ubuntu-latest
        timeout-minutes: 8
        steps: 
         - name: Docker user name
           run: echo " ${{ vars.DOCKER_USER_NAME }} "
         - name: Docker Secret 
           run: echo " this is the secret ${{ secrets.DOCKER_SECRET}}"
         - name: sleep 
           timeout-minutes: 1 
           run: sleep 800

