name: Generate ASCII Using Multiple Jobs
on: push
jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:

          - name: Install Cosway CLI
            run: sudo apt-get install cowsay -y 
        
          - name: Execute Cosway CMD
            run: cowsay -f dragon "RUN i am dragon" > dragon.txt

          - name: Upload Dragon text file
            uses: actions/upload-artifact@v4
            with:
                name: dragon-text-file
                path: dragon.txt
    test_job:
        runs-on: ubuntu-latest
        needs: build_job
        steps:
          - name: Get Dragon file
            uses: actions/download-artifact@v4
            with:
                name: dragon-text-file
          - name: Check if file exists
            run:  grep -i "dragon" dragon.txt

    deploy_job:
        runs-on: ubuntu-latest
        needs: [test_job]
        steps:
         - name: Get Dragon file
           uses: actions/download-artifact@v4
           with:
                name: dragon-text-file
         - name: Read the file
           run:  cat dragon.txt
         - name: Deploy
           run: echo "Deploying"
