name: Generate ASCII Using Multiple Jobs
on: push
jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:

          - name: Install Cosway CLI
            run: sudo apt-get install cowsay -y 
        
          - name: Execute Cosway CMD
            run: cowsay -f dragon "RUN i am dragon" > dragon.txt

          - name: Sleep for 30 seconds
            run: sleep 30 
    test_job:
        runs-on: ubuntu-latest
        needs: build_job
        steps:
          - name: Sleep for 10 seconds
            run: sleep 10
          - name: Check if file exists
            run:  grep -i "dragon" dragon.txt

    deploy_job:
        runs-on: ubuntu-latest
        needs: [test_job]
        steps:
          - name: Read the file
            run:  cat dragon.txt
          - name: Deploy
            run: echo "Deploying"
